App\Faceting\DTO\Management\Facet\FacetUpsertDTO:
  properties:
    code:
      - NotBlank: ~
      - Length:
          max: 64
      - Regex:
          pattern: '/^[A-Za-z0-9_-]+$/'
    nameEntity:
      - NotBlank: ~
      - Length:
          max: 255
    type:
      - Choice:
          choices:
            - term
            - range
            - boolean
            - hierarchy
